### ISSUE TITLE
npm throws Error: cannot find module

### ISSUE THREAD

**Issue by Marcarrian** [coreybutler/nvm-windows#673]
**Issue:**
I installed the version 1.1.7 and setup a proxy (since that does not seem to work with version 1.1.8 as it already has been stated here https://github.com/coreybutler/nvm-windows/issues/670). Then I installed the node version 14.18.0 with nvm. `node -v` correctly returns said version. However, when using any `npm` command, the following error is thrown:

λ npm --version                                                                             
internal/modules/cjs/loader.js:905                                                          
  throw err;                                                                                
  ^                                                                                         
                                                                                            
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'         
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)             
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)                        
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)     
    at internal/main/run_main_module.js:17:47 {                                             
  code: 'MODULE_NOT_FOUND',                                                                 
  requireStack: []                                                                          
}

**How To Reproduce:**
As described above.

**Expected Behavior:**
Any npm command should work as expected.

**Desktop:**
 - OS: Windows 10

**Comment by coreybutler** [comment]
Did you have Node installed before installing NVM4W?

**Comment by Marcarrian** [comment]
No I did not. However I've since simply installed nodejs manually so I'm closing this.

**Comment by coreybutler** [comment]
For anyone arriving via Google, see the third most common issue at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied (which is the most common reason for not recognizing npm).
