### ISSUE TITLE
Version 1.1 missing settings.txt

### ISSUE THREAD

**Issue by SteveALee** [coreybutler/nvm-windows#118]
I installed 1.1 after uninstalling nvm-windows and continuously get the following error

`ERROR open \settings.txt: The system cannot find the file specified.`

All is well if I install the previous version and then install 1.1 over it.

**Comment by JimBTek** [comment]
I ran into this issue as well. Fixed with SteveALee's resolution. Thanks!

**Comment by mithun-daa** [comment]
+1

**Comment by FranciscoGileno** [comment]
+1

**Comment by simonealessandrelli** [comment]
+1
SeveALee's resolution method doesn't work for me

**Comment by mithun-daa** [comment]
Unfortunately, I just ended up installing `nodist`[here](https://github.com/marcelklehr/nodist). Neither `nvmw` or `nvm-windows` worked for me. It probably was just a configuration issue but in lieu of time I had to switch to nodist. It worked right out of the box.

**Comment by zlm919** [comment]
I create settings.txt in the installation directory manual
https://github.com/coreybutler/nvm-windows/wiki#manual-installation

**Comment by BrainCrumbz** [comment]
Here some steps that might help figuring out what's going:

1. I just installed nvm-windows through installer, for the first time on this machine
1. At the end of setup wizard I left the *run cmd* check box enabled
1. Command prompt window opened and I saw the mentioned error message
1. I then opened another command prompt and typed `nvm`, and just saw the same message
1. I then opened a command prompt as administrator, and ran `nvm`. This time, the help came out, no error message.
1. I open a regular prompt then, ran `nvm` and no error message anymore, just help.

HTH

**Comment by turbidwater** [comment]
Following @BrainCrumbz tips, running as admin works for me. However, when I open up a regular cmd, I get the following error when I run nvm:
module.js:340
    throw err;
          ^
Error: Cannot find module './nvm-help'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Nils\AppData\Roaming\npm\node_modules\nvm\bin\nvm:24:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by SteveALee** [comment]
I just did a clean installation and also get the missing file error in the COmmand window launched by setup even though C:\Users\<username>\AppData\Roaming\nvm\settigs/.txt exists.

**Comment by rebolyte** [comment]
+1 I can also only run it as administrator.

**Comment by vicneanschi** [comment]
Same experience as @BrainCrumbz

**Comment by sah2ed** [comment]
I can also confirm that @BrainCrumbz's work around works on Windows 8.1.

**Comment by semi-xi** [comment]
+1 I can also only run it as administrator.

**Comment by cpb** [comment]
:+1: can only run it as administrator, and, running it as administrator modifies how it runs as a normal user.

1. Install
2. Run nvm in cmd.exe as normal user => settings.txt not found
3. Run nvm in cmd.exe as administrator => help message
4. Run nvm in cmd.exe as normal user => command nvm not found

**Comment by simonknittel** [comment]
+1 exactly the same issue as @cpb

**Comment by A86S** [comment]
Thanks @BrainCrumbz its works

**Comment by jpierson** [comment]
I ran into this issue as well. Running Powershell has admin first and running the nvm command seemed to fix it for subsequently opened Powershell instances. After attempting `nvm install latest` and then `nvm use 6.2.2` though the expected `node` and `npm` commands do not appear available. Seems to me something was botched in the install.

**Comment by coreybutler** [comment]
Part of this issue was due to a problem in the sequence of when the installer completed creation of the settings.txt file (the CMD prompt opened before completion). Part of it was another sequencing issue with the registry.

A final part to all of this is botched downloads... as in a node download wasn't always completing. There's nothing I can do about the network, but I did switch the list of versions from nodedistro (a repo I maintained partially by hand before node got around to an official list). Now NVM4W is using the official node release list. It should be referencing the same download links you would if you were to download directly from nodejs.org.

This issue has frustrated far too many people (myself included) for far too long. I scrapped the option to automatically open a command prompt from the installer in  NVM4W 1.1.1. In my tests, I can no longer create this error.
